# -*- coding: utf-8 -*-
"""bmiapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCxX7fBHxQoQsP4O7xMraW9o27zFdvLt
"""

import streamlit as st
import pandas as pd
import os
from datetime import datetime

st.title("BMI Calculator App 💪")

# -----------------------------
# Helper functions
# -----------------------------
def calculate_bmi(weight, height):
    height_m = height / 100  # convert cm to meters
    return round(weight / (height_m ** 2), 2)

def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal"
    elif 24.9 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Obese"

def meal_plan(category):
    plans = {
        "Underweight": {
            "Meal Plan": [
                "High-calorie smoothies",
                "Peanut butter & whole grains",
                "Paneer, eggs, bananas, nuts"
            ],
            "Exercise": ["Light strength training", "Yoga", "Walking"]
        },
        "Normal": {
            "Meal Plan": [
                "Balanced diet of carbs, proteins, healthy fats",
                "Fruits, vegetables, dal-chawal, chapati, salads"
            ],
            "Exercise": ["Jogging", "Cycling", "30 min daily walk"]
        },
        "Overweight": {
            "Meal Plan": [
                "Low sugar, low fat",
                "High protein, high fiber",
                "Avoid fried foods"
            ],
            "Exercise": ["Cardio 30 min", "Yoga", "Brisk walking"]
        },
        "Obese": {
            "Meal Plan": [
                "High fiber vegetables",
                "Lean proteins",
                "Avoid sugary drinks, junk food"
            ],
            "Exercise": ["Walking 45 min", "Swimming", "Low-impact workouts"]
        }
    }
    return plans[category]

# -----------------------------
# User Inputs
# -----------------------------
st.header("Enter Your Details")

name = st.text_input("Name")
age = st.number_input("Age", min_value=1, max_value=120)
gender = st.selectbox("Gender", ["Male", "Female", "Other"])
height = st.number_input("Height (cm)", min_value=1.0)
weight = st.number_input("Weight (kg)", min_value=1.0)

if st.button("Calculate BMI"):
    if height > 0 and weight > 0:
        bmi = calculate_bmi(weight, height)
        category = bmi_category(bmi)

        st.success(f"Your BMI is: **{bmi}**")
        st.info(f"Category: **{category}**")

        # Show meal + exercise suggestions
        plan = meal_plan(category)
        st.subheader("Recommended Meal Plan")
        for item in plan["Meal Plan"]:
            st.write("- " + item)

        st.subheader("Light Exercise Suggestions")
        for ex in plan["Exercise"]:
            st.write("- " + ex)

        # -----------------------------
        # Save Data for Future Use
        # -----------------------------
        data_file = "bmi_data.csv"
        new_entry = {
            "Timestamp": datetime.now(),
            "Name": name,
            "Age": age,
            "Gender": gender,
            "Height(cm)": height,
            "Weight(kg)": weight,
            "BMI": bmi,
            "Category": category
        }

        if os.path.exists(data_file):
            df = pd.read_csv(data_file)
            df = df._append(new_entry, ignore_index=True)
        else:
            df = pd.DataFrame([new_entry])

        df.to_csv(data_file, index=False)
        st.success("Your data has been saved!")

# -----------------------------
# View previous data
# -----------------------------
st.subheader("Previous BMI Records")

if os.path.exists("bmi_data.csv"):
    df = pd.read_csv("bmi_data.csv")
    st.dataframe(df)